#! /bin/bash

wd=`pwd`

#echo "\"cd('${wd}');fprintf('${@}');exit\""

#echo \""cd('${wd}');$1(${@:2});exit\""

#matlab -nojvm -nodesktop -nodisplay -nosplash -r "cd('${wd}');$@;exit"




if [ "$1" == "-f" ] # use the -f flag to force interpreter abortion on error.
then
    args="$3"
    for i in ${@:4}; do args=`echo $args,"$i"`; done

    matlab -nojvm -nodesktop -nodisplay -nosplash -r "try cd('${wd}');$2($args);exit; catch; exit(1); end"
else
    args="$2"
    for i in ${@:3}; do args=`echo $args,"$i"`; done

    matlab -nojvm -nodesktop -nodisplay -nosplash -r "cd('${wd}');$1($args);exit;"
fi

stty sane

