#! /bin/bash

wd=`pwd`

#echo "\"cd('${wd}');fprintf('${@}');exit\""

#echo \""cd('${wd}');$1(${@:2});exit\""

#matlab -nojvm -nodesktop -nodisplay -nosplash -r "cd('${wd}');$@;exit"


if [ "$1" == "-f" ] # use the -f flag to force interpreter abortion on error.
then
    matlab -nojvm -nodesktop -nodisplay -nosplash -r "try cd('${wd}');$2(${@:3});exit; catch; exit(1); end"
else
    matlab -nojvm -nodesktop -nodisplay -nosplash -r "cd('${wd}');$1(${@:2});exit;"
fi



