#! /bin/bash


output_folder="sounds"


rm -rf ${output_folder}/*

# N > simulation.log
echo $# > simulation.log

i=0
for file in "$@"
do
    sox "$file" "${output_folder}/s${i}x0.wav" remix 1
    sox "$file" "${output_folder}/s${i}x1.wav" remix 2
    i=$((i+1))
    # alpha delta >> simulation.log
    alpha_delta.py "$file" >> simulation.log
done

cd "${output_folder}"

if [[ $# > 1 ]]
then
    sox -m `ls s*x0.wav` x0.wav
    sox -m `ls s*x1.wav` x1.wav
else
    cp s0x0.wav x0.wav 
    cp s0x1.wav x1.wav 
fi



